# Generated by Django 2.0.9 on 2018-10-19 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False, verbose_name='Category ID')),
                ('category_name', models.CharField(db_column='CategoryName', db_index=True, max_length=15, verbose_name='Category name')),
                ('description', models.TextField(blank=True, db_column='Description', null=True, verbose_name='Description')),
                ('picture', models.BinaryField(blank=True, db_column='Picture', null=True, verbose_name='Picture')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CustomerDemographics',
            fields=[
                ('customer_type_id', models.CharField(db_column='CustomerTypeID', max_length=5, primary_key=True, serialize=False, verbose_name='Customer typeID')),
                ('customer_desc', models.TextField(blank=True, db_column='CustomerDesc', null=True, verbose_name='Customer description')),
            ],
            options={
                'db_table': 'customerdemographics',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(db_column='CustomerID', max_length=5, primary_key=True, serialize=False, verbose_name='Customer ID')),
                ('company_name', models.CharField(db_column='CompanyName', max_length=40, verbose_name='Company name')),
                ('contact_name', models.CharField(blank=True, db_column='ContactName', max_length=30, null=True, verbose_name='Contact name')),
                ('contact_title', models.CharField(blank=True, db_column='ContactTitle', max_length=30, null=True, verbose_name='Contact title')),
                ('address', models.CharField(blank=True, db_column='Address', max_length=60, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, db_column='City', max_length=15, null=True, verbose_name='City')),
                ('region', models.CharField(blank=True, db_column='Region', max_length=15, null=True, verbose_name='Region')),
                ('postal_code', models.CharField(blank=True, db_column='PostalCode', max_length=10, null=True, verbose_name='Postal code')),
                ('country', models.CharField(blank=True, db_column='Country', max_length=15, null=True, verbose_name='Country')),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=24, null=True, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=24, null=True, verbose_name='Fax')),
                ('customer_customer_demo', models.ManyToManyField(blank=True, db_table='CustomerCustomerDemo', to='northwind.CustomerDemographics', verbose_name='Customer customer demo')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(db_column='EmployeeID', primary_key=True, serialize=False, verbose_name='Employee id')),
                ('last_name', models.CharField(db_column='LastName', db_index=True, max_length=20, verbose_name='Last name')),
                ('first_name', models.CharField(db_column='FirstName', max_length=10, verbose_name='First name')),
                ('title', models.CharField(blank=True, db_column='Title', max_length=30, null=True, verbose_name='title')),
                ('title_of_courtesy', models.CharField(blank=True, db_column='TitleOfCourtesy', max_length=25, null=True, verbose_name='Title of Courtesy')),
                ('birth_date', models.DateTimeField(blank=True, db_column='BirthDate', null=True, verbose_name='Birth date')),
                ('hire_date', models.DateTimeField(blank=True, db_column='HireDate', null=True, verbose_name='Hire date')),
                ('address', models.CharField(blank=True, db_column='Address', max_length=60, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, db_column='City', max_length=15, null=True, verbose_name='City')),
                ('region', models.CharField(blank=True, db_column='Region', max_length=15, null=True, verbose_name='Region')),
                ('postal_code', models.CharField(blank=True, db_column='PostalCode', db_index=True, max_length=10, verbose_name='Postal code')),
                ('country', models.CharField(blank=True, db_column='Country', max_length=15, null=True, verbose_name='Country')),
                ('home_phone', models.CharField(blank=True, db_column='HomePhone', max_length=24, null=True, verbose_name='Home phone')),
                ('extension', models.CharField(blank=True, db_column='Extension', max_length=4, null=True, verbose_name='Extension')),
                ('photo', models.BinaryField(blank=True, db_column='Photo', null=True, verbose_name='Photo')),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True, verbose_name='Notes')),
                ('photo_path', models.CharField(blank=True, db_column='PhotoPath', max_length=255, null=True, verbose_name='Photo path')),
                ('reports_to', models.ForeignKey(blank=True, db_column='ReportsTo', null=True, on_delete=django.db.models.deletion.PROTECT, to='northwind.Employees')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=4, max_digits=19, verbose_name='Unit price')),
                ('quantity', models.SmallIntegerField(db_column='Quantity', verbose_name='Quantity')),
                ('discount', models.FloatField(db_column='Discount', verbose_name='Discount')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(db_column='OrderID', primary_key=True, serialize=False, verbose_name='Order ID')),
                ('order_date', models.DateField(blank=True, db_column='OrderDate', db_index=True, null=True, verbose_name='Order date')),
                ('required_date', models.DateField(blank=True, db_column='RequiredDate', null=True, verbose_name='Required_date')),
                ('shipped_date', models.DateField(blank=True, db_column='ShippedDate', db_index=True, null=True, verbose_name='Shipped date')),
                ('freight', models.DecimalField(blank=True, db_column='Freight', decimal_places=4, max_digits=19, null=True, verbose_name='Freight')),
                ('ship_name', models.CharField(blank=True, db_column='ShipName', max_length=40, null=True, verbose_name='Ship name')),
                ('ship_address', models.CharField(blank=True, db_column='ShipAddress', max_length=60, null=True, verbose_name='Ship address')),
                ('ship_city', models.CharField(blank=True, db_column='ShipCity', max_length=15, null=True, verbose_name='Ship city')),
                ('ship_region', models.CharField(blank=True, db_column='ShipRegion', max_length=15, null=True, verbose_name='Ship region')),
                ('ship_postal_code', models.CharField(blank=True, db_column='ShipPostalCode', db_index=True, max_length=10, null=True, verbose_name='Ship postal code')),
                ('ship_country', models.CharField(blank=True, db_column='ShipCountry', max_length=15, null=True, verbose_name='Shipped country')),
                ('customer', models.ForeignKey(blank=True, db_column='CustomerID', null=True, on_delete=django.db.models.deletion.CASCADE, to='northwind.Customers')),
                ('employee', models.ForeignKey(blank=True, db_column='EmployeeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='northwind.Employees')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(db_column='ProductID', primary_key=True, serialize=False, verbose_name='Product ID')),
                ('product_name', models.CharField(db_column='ProductName', db_index=True, max_length=40, verbose_name='Product name')),
                ('quantity_per_unit', models.CharField(blank=True, db_column='QuantityPerUnit', max_length=20, null=True, verbose_name='Quantity per Unit')),
                ('unit_price', models.DecimalField(blank=True, db_column='UnitPrice', decimal_places=4, max_digits=19, null=True, verbose_name='Unit price')),
                ('units_in_stock', models.SmallIntegerField(blank=True, db_column='UnitsInStock', null=True, verbose_name='Units in Stock')),
                ('units_on_order', models.SmallIntegerField(blank=True, db_column='UnitsOnOrder', null=True, verbose_name='Units on Order')),
                ('reorder_level', models.SmallIntegerField(blank=True, db_column='ReorderLevel', null=True, verbose_name='Reorder level')),
                ('discontinued', models.IntegerField(db_column='Discontinued', verbose_name='Discontinued')),
                ('category_id', models.ForeignKey(blank=True, db_column='CategoryID', null=True, on_delete=django.db.models.deletion.CASCADE, to='northwind.Categories')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.PositiveSmallIntegerField(db_column='RegionID', primary_key=True, serialize=False, verbose_name='Region id')),
                ('region_description', models.CharField(db_column='RegionDescription', max_length=50, verbose_name='Region description')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('shipper_id', models.AutoField(db_column='ShipperID', primary_key=True, serialize=False, verbose_name='Shipper ID')),
                ('company_name', models.CharField(db_column='CompanyName', max_length=40, verbose_name='Company name')),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=24, null=True, verbose_name='Phone')),
            ],
            options={
                'db_table': 'shippers',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(db_column='SupplierID', primary_key=True, serialize=False, verbose_name='Supplier ID')),
                ('company_name', models.CharField(db_column='CompanyName', max_length=40, verbose_name='Company name')),
                ('contact_name', models.CharField(blank=True, db_column='ContactName', max_length=30, null=True, verbose_name='Contact name')),
                ('contact_title', models.CharField(blank=True, db_column='ContactTitle', max_length=30, null=True, verbose_name='Contact title')),
                ('address', models.CharField(blank=True, db_column='Address', max_length=60, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, db_column='City', max_length=15, null=True, verbose_name='City')),
                ('region', models.CharField(blank=True, db_column='Region', max_length=15, null=True, verbose_name='Region')),
                ('postal_code', models.CharField(blank=True, db_column='PostalCode', max_length=10, null=True, verbose_name='Postal code')),
                ('country', models.CharField(blank=True, db_column='Country', max_length=15, null=True, verbose_name='Country')),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=24, null=True, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=24, null=True, verbose_name='Fax')),
                ('homepage', models.TextField(blank=True, db_column='HomePage', null=True, verbose_name='HomePage')),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Territories',
            fields=[
                ('territory_id', models.CharField(db_column='TerritoryID', max_length=20, primary_key=True, serialize=False, verbose_name='Territory id')),
                ('territory_description', models.CharField(db_column='TerritoryDescription', max_length=50, verbose_name='Territory description')),
                ('region_id', models.ForeignKey(db_column='RegionID', on_delete=django.db.models.deletion.CASCADE, to='northwind.Region')),
            ],
            options={
                'db_table': 'territories',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='supplier_id',
            field=models.ForeignKey(blank=True, db_column='SupplierID', null=True, on_delete=django.db.models.deletion.CASCADE, to='northwind.Suppliers'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_details',
            field=models.ManyToManyField(blank=True, through='northwind.OrderDetails', to='northwind.Products', verbose_name='Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ship_via',
            field=models.ForeignKey(blank=True, db_column='ShipVia', null=True, on_delete=django.db.models.deletion.CASCADE, to='northwind.Shippers'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_id',
            field=models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='northwind.Orders'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product_id',
            field=models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='northwind.Products'),
        ),
        migrations.AddField(
            model_name='employees',
            name='territories',
            field=models.ManyToManyField(blank=True, db_table='EmployeeTerritories', to='northwind.Territories', verbose_name='Territories'),
        ),
    ]
